-- MySQL Script generated by MySQL Workbench
-- Tue Aug 28 10:21:23 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`civilizations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`civilizations` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `date_of_beginning` DATETIME NOT NULL,
  `date_of_end` DATETIME NULL,
  `population` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`religions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`religions` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `number_of_devoted` INT UNSIGNED NOT NULL,
  `god_name` VARCHAR(50) NULL,
  `prophet_name` VARCHAR(50) NULL,
  `type` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tortures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tortures` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `origin` VARCHAR(50) NOT NULL,
  `suffering_type` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`creatures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`creatures` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `origin` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ranks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ranks` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hell_staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`hell_staff` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `age` INT UNSIGNED NOT NULL,
  `id_creatures` INT UNSIGNED NOT NULL,
  `id_ranks` INT UNSIGNED NOT NULL,
  `id_tortures` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_creatures_tortures_idx` (`id_tortures` ASC),
  INDEX `fk_hell_staff_creatures_idx` (`id_creatures` ASC),
  INDEX `fk_helll_staff_ranks_idx` (`id_ranks` ASC),
  CONSTRAINT `fk_hell_staff_tortures`
    FOREIGN KEY (`id_tortures`)
    REFERENCES `mydb`.`tortures` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hell_staff_creatures`
    FOREIGN KEY (`id_creatures`)
    REFERENCES `mydb`.`creatures` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_helll_staff_ranks`
    FOREIGN KEY (`id_ranks`)
    REFERENCES `mydb`.`ranks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`humans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`humans` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `last_name` VARCHAR(255) NOT NULL,
  `first_name` VARCHAR(255) NOT NULL,
  `age_at_death` INT UNSIGNED NOT NULL,
  `gender` CHAR(1) NOT NULL,
  `date_of_arrival` DATETIME NOT NULL,
  `death_cause` VARCHAR(50) NOT NULL,
  `reason_of_presence` VARCHAR(50) NOT NULL,
  `id_civilizations` INT UNSIGNED NOT NULL,
  `id_religions` INT UNSIGNED NOT NULL,
  `id_tortures` INT UNSIGNED NOT NULL,
  `id_hell_staff` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_civilizations_idx` (`id_civilizations` ASC),
  INDEX `fk_religions_idx` (`id_religions` ASC),
  INDEX `fk_tortures_idx` (`id_tortures` ASC),
  INDEX `fk_hell_staff_idx` (`id_hell_staff` ASC),
  CONSTRAINT `fk_civilizations`
    FOREIGN KEY (`id_civilizations`)
    REFERENCES `mydb`.`civilizations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_religions`
    FOREIGN KEY (`id_religions`)
    REFERENCES `mydb`.`religions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tortures`
    FOREIGN KEY (`id_tortures`)
    REFERENCES `mydb`.`tortures` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hell_staff`
    FOREIGN KEY (`id_hell_staff`)
    REFERENCES `mydb`.`hell_staff` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`country_codes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`country_codes` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `country_code` CHAR(3) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`types` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hell_places`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`hell_places` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `humans_population` INT UNSIGNED NOT NULL,
  `creatures_population` INT UNSIGNED NOT NULL,
  `id_types` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_types_idx` (`id_types` ASC),
  CONSTRAINT `fk_types`
    FOREIGN KEY (`id_types`)
    REFERENCES `mydb`.`types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`link_civlizations_religions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`link_civlizations_religions` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_religions` INT UNSIGNED NOT NULL,
  `id_civilizations` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `id_religions`, `id_civilizations`),
  INDEX `fk_link_religions` (`id_religions` ASC),
  INDEX `fk_link_civilizations` (`id_civilizations` ASC),
  CONSTRAINT `fk_link_religions`
    FOREIGN KEY (`id_religions`)
    REFERENCES `mydb`.`religions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_link_civilizations`
    FOREIGN KEY (`id_civilizations`)
    REFERENCES `mydb`.`civilizations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`link_hell_places_religions_creatures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`link_hell_places_religions_creatures` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_hell_places` INT UNSIGNED NOT NULL,
  `id_religions` INT UNSIGNED NOT NULL,
  `id_creatures` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `id_hell_places`, `id_religions`, `id_creatures`),
  INDEX `id_hell_places` (`id_hell_places` ASC),
  INDEX `id_religions` (`id_religions` ASC),
  INDEX `id_creatures` (`id_creatures` ASC),
  CONSTRAINT `fk_link_hell_places`
    FOREIGN KEY (`id_hell_places`)
    REFERENCES `mydb`.`hell_places` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_link_religions`
    FOREIGN KEY (`id_religions`)
    REFERENCES `mydb`.`religions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_link_creatures`
    FOREIGN KEY (`id_creatures`)
    REFERENCES `mydb`.`creatures` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`link_country_codes_civilizations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`link_country_codes_civilizations` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_country_codes` INT UNSIGNED NOT NULL,
  `id_civilizations` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `id_country_codes`, `id_civilizations`),
  INDEX `fk_link_country_codes` (`id_country_codes` ASC),
  INDEX `fk_civilizations` (`id_civilizations` ASC),
  CONSTRAINT `fk_link_country_codes`
    FOREIGN KEY (`id_country_codes`)
    REFERENCES `mydb`.`country_codes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_link_civilizations`
    FOREIGN KEY (`id_civilizations`)
    REFERENCES `mydb`.`civilizations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`residentPlace`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`residentPlace` (`last_name` INT, `first_name` INT, `name` INT);

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`employeeWorks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employeeWorks` (`last_name` INT, `first_name` INT, `name` INT);

-- -----------------------------------------------------
-- procedure ten_requests
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE PROCEDURE `ten_requests` ()
BEGIN
SELECT COUNT(id) FROM humans;

SELECT last_name, first_name FROM humans ORDER BY date_of_arrival DESC LIMIT 0,1;

SELECT name FROM creatures WHERE name LIKE "B%";

SELECT COUNT(h.id) FROM humans AS h JOIN hell_staff AS s ON s.id=h.id WHERE s.name="Belphegor";

SELECT AVG(age_at_death) FROM humans;

SELECT name FROM religions WHERE id=(SELECT MAX(number_of_devoted) FROM religions);

SELECT COUNT(DISTINCT name) FROM civilizations;

SELECT c.name FROM creatures c JOIN hell_places h ON h.id=c.id WHERE 1 
AND h.name="Erebe" 
AND h.id=(SELECT MAX(creatures_population) FROM h);

SELECT name FROM tortures GROUP BY suffering_type;

SELECT c.name, COUNT(DISTINCT p.country_codes) AS NbCountry FROM civilizations AS c, country_codes AS p 
ORDER BY NbCountry DESC LIMIT 1;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- View `mydb`.`residentPlace`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`residentPlace`;
USE `mydb`;
CREATE  OR REPLACE VIEW residentPlace AS SELECT h.last_name, h.first_name, p.name FROM humans h JOIN hell_places p ON p.id = h.id;

-- -----------------------------------------------------
-- View `mydb`.`employeeWorks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`employeeWorks`;
USE `mydb`;
CREATE  OR REPLACE VIEW employeeWorks AS SELECT h.last_name, h.first_name, s.name FROM humans h JOIN hell_staff s ON s.id = h.id;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
